access/config/routes.rb
Rails.application.routes.draw do
  root 'people#index', locale: :en
  get '/:locale' => 'people#index', as: 'verify_email'
  get '/:locale/:user_id/csr' => 'csr_gen#mozilla_csr'
  post '/:locale/:user_id/submit' => 'csr_gen#csr_submission'
  get '/:locale/error_csr_sub' => 'csr_gen#error_csr_sub'
  get '/:locale/find_csr' => 'csr_gen#find_csr'
  post '/:locale/find_csr' => 'csr_gen#csr_value'
  get '/:locale/find_csr/no_csr' => 'csr_gen#error'
  get '/:locale/ra/csr_list' => 'ra#csr_list'
  get '/:locale/ra/csr_pending' => 'ra#csr_pending'
  get '/:locale/ra/csr_approved' => 'ra#csr_approved'
  get '/:locale/ra/csr_rejected' => 'ra#csr_rejected'
  scope ":locale", locale: /#{APP_CONFIG['available_locales'].join('|')}/ do
      resources :people do
        get 'versions' => 'people_versions#index'
      end
      get '/people/confirm_email/:token' => 'people#verify_email'

      resources :organizations
      resources :hosts do
        get 'versions' => 'hosts_versions#index'
      end
      resources :certificate_requests, except: [:edit] do
        post 'approve' => 'certificate_requests#approve_csr', as: 'approve'
        post 'reject' => 'certificate_requests#reject_csr', as: 'reject'
      end
      get '/signup' => 'people#new'
      get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      get '/logout' => 'sessions#destroy'
  end

end

access/app/models/certificate_request.rb
require 'exceptions/invalid_action'

class CertificateRequest < ActiveRecord::Base
  # Associations
  belongs_to :requestor,
             class_name: 'Person',
             foreign_key: 'requestor_id'

  belongs_to :owner_dn,
             class_name: 'DistinguishedName',
             foreign_key: 'owner_dn_id'

  belongs_to :organization

  # Validations
  validates :status, presence: true, allow_nil: false
  validates_inclusion_of :status, in: %w(pending rejected signed approved)
  validates :body, presence: true, csr: true
  validates :uuid, presence: true, uniqueness: true
  validates :csr_type, presence: true, allow_nil: false
  validates_inclusion_of :csr_type, in: %w(classic spkac classic_ie vista_ie)
  validates :requestor_id, presence: true
  validates :owner_dn_id, presence: true, uniqueness: true
  validates :organization_id, presence: true

  def self.approve_csr(csr_id)
    csr = CertificateRequest.find(csr_id)
    if csr.status == 'pending'
      csr.status = 'approved'
      csr.save!
    else
      raise InvalidActionError.new("#{I18n.t "exceptions.invalid_action.approve_csr"} #{csr.status}")
    end
  end

  def self.reject_csr(csr_id)
    csr = CertificateRequest.find(csr_id)
    if csr.status == 'pending'
      csr.status = 'rejected'
      csr.save!
    else
      raise InvalidActionError.new("#{I18n.t "exceptions.invalid_action.reject_csr"} #{csr.status}")
    end
  end
end

access/app/controllers/certificate_requests_controller.rb
require 'helpers/x509_helpers'

class CertificateRequestsController < ApplicationController
  before_action :set_certificate_request, only: [:show, :edit, :update, :destroy]

  # GET /certificate_requests
  # GET /certificate_requests.json
  def index
    @certificate_requests = CertificateRequest.all
  end

  # GET /certificate_requests/1
  # GET /certificate_requests/1.json
  def show
  end

  # GET /certificate_requests/new
  def new
    @certificate_request = CertificateRequest.new
  end

  # GET /certificate_requests/1/edit
  def edit
  end

  # POST /certificate_requests
  # POST /certificate_requests.json
  def create
    @certificate_request = CertificateRequest.new(certificate_request_params)
    X509Helpers.csr_creation(@certificate_request, params)

    respond_to do |format|
      if @certificate_request.save
        format.html { redirect_to certificate_requests_url, notice: 'Certificate request was successfully created.' }
        format.json { render :show, status: :created, location: @certificate_request }
      else
        if (@certificate_request.errors['body'])
          @certificate_request.errors.each do |k,v|
            @certificate_request.errors.delete(k) unless k == :body
          end
        end
        format.html { render :new }
        format.json { render json: @certificate_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificate_requests/1
  # PATCH/PUT /certificate_requests/1.json
  def update
    respond_to do |format|
      if @certificate_request.update(certificate_request_params)
        format.html { redirect_to @certificate_request, notice: 'Certificate request was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate_request }
      else
        format.html { render :edit }
        format.json { render json: @certificate_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificate_requests/1
  # DELETE /certificate_requests/1.json
  def destroy
    @certificate_request.destroy
    respond_to do |format|
      format.html { redirect_to certificate_requests_url, notice: 'Certificate request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve_csr
    begin
      CertificateRequest.approve_csr(params[:certificate_request_id])
    rescue InvalidActionError => e
      redirect_to certificate_requests_url, flash: { error: "#{e.message}" }
      return
    end
    redirect_to certificate_requests_url, notice: "Updated!"
  end

  def reject_csr
    begin
      CertificateRequest.reject_csr(params[:certificate_request_id])
    rescue InvalidActionError => e
      redirect_to certificate_requests_url, flash: { error: "#{e.message}" }
      return
    end
    redirect_to certificate_requests_url, notice: "Updated!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate_request
      @certificate_request = CertificateRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_request_params
      params.require(:certificate_request).permit(:body)
    end
end

access/app/helpers/certificate_requests_helper.rb
module CertificateRequestsHelper
end

access/app/views/certificate_requests/_form.html.erb
<%= form_for(@certificate_request) do |f| %>
    <% if @certificate_request.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@certificate_request.errors.count, "error") %> prohibited this certificate_request from
            being saved:</h2>

          <ul>
            <% @certificate_request.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= label_tag I18n.t("views.label.certificate_request.owner") %>
      <%= select_tag(:owner_id, options_from_collection_for_select(Person.all, :id, :email)) %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

access/app/views/certificate_requests/index.html.erb
<p id="notice"><%= notice %></p>
<p id="error"><%= flash[:error] %></p>

<h1><%= I18n.t('views.list_csr') %></h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t "views.label.certificate_request.uuid"%></th>
      <th><%= I18n.t "views.label.certificate_request.status"%></th>
      <th><%= I18n.t "views.label.certificate_request.owner"%></th>
      <th><%= I18n.t "views.label.certificate_request.organization"%></th>
      <th colspan="2"></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificate_requests.each do |certificate_request| %>
      <tr>
        <td><%= certificate_request.uuid %>></td>
        <td><%= certificate_request.status %>></td>
        <td><%= certificate_request.owner_dn.subject_dn %>></td>
        <td><%= certificate_request.organization.name %>></td>
        <td><%= link_to I18n.t("views.show"), certificate_request %></td>
        <td><%= link_to I18n.t("views.destroy"), certificate_request, method: :delete, data: { confirm: I18n.t("views.delete_confirmation") } %></td>
        <td><%= link_to I18n.t("views.accept"), certificate_request_approve_url(certificate_request), method: :post, data: {confirm: I18n.t("views.delete_confirmation") }%></td>
        <td><%= link_to I18n.t("views.reject"), certificate_request_reject_url(certificate_request), method: :post, data: { confirm: I18n.t("views.delete_confirmation") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.new_csr'), new_certificate_request_path %>

access/app/views/certificate_requests/new.html.erb
<h1><%= I18n.t('views.new_csr') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), certificate_requests_path %>

access/app/views/certificate_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.uuid" %>:</strong>
  <%= @certificate_request.uuid %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.body" %>:</strong>
  <%= @certificate_request.body %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.requestor" %>:</strong>
  <%= @certificate_request.requestor %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.owner" %>:</strong>
  <%= @certificate_request.owner_dn.subject_dn %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.organization" %>:</strong>
  <%= @certificate_request.organization.name %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.status" %>:</strong>
  <%= @certificate_request.status %>
</p>

<%= link_to 'Back', certificate_requests_path %>