access/config/routes.rb
Rails.application.routes.draw do
  root 'people#index', locale: :en
  get '/:locale' => 'people#index', as: 'verify_email'
  get '/:locale/:user_id/csr' => 'csr_gen#mozilla_csr'
  post '/:locale/:user_id/submit' => 'csr_gen#csr_submission'
  get '/:locale/error_csr_sub' => 'csr_gen#error_csr_sub'
  get '/:locale/find_csr' => 'csr_gen#find_csr'
  post '/:locale/find_csr' => 'csr_gen#csr_value'
  get '/:locale/find_csr/no_csr' => 'csr_gen#error'
  get '/:locale/ra/csr_list' => 'ra#csr_list'
  get '/:locale/ra/csr_pending' => 'ra#csr_pending'
  get '/:locale/ra/csr_approved' => 'ra#csr_approved'
  get '/:locale/ra/csr_rejected' => 'ra#csr_rejected'
  scope ":locale", locale: /#{APP_CONFIG['available_locales'].join('|')}/ do
      resources :people do
        get 'versions' => 'people_versions#index'
      end
      get '/people/confirm_email/:token' => 'people#verify_email'

      resources :organizations
      resources :hosts do
        get 'versions' => 'hosts_versions#index'
      end
      resources :certificate_requests, except: [:edit] do
        post 'approve' => 'certificate_requests#approve_csr', as: 'approve'
        post 'reject' => 'certificate_requests#reject_csr', as: 'reject'
      end
      get '/signup' => 'people#new'
      get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      get '/logout' => 'sessions#destroy'
  end

end

access/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :people

  validates :domain, uniqueness: { case_sensitive: false }, presence: true
  validates :name, presence: true

  translates :name, :description
end

access/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :domain, :description)
    end
end

access/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

access/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

access/app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

access/app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Domain</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.domain %></td>
        <td><%= organization.description %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

access/app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

access/app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @organization.domain %>
</p>

<p>
  <strong>Description:</strong>
  <%= @organization.description %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>